[package]
name = "minigrep"
version = "0.1.0"
authors = ["haric95 <hari-c@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
